services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'imageboard'
      MYSQL_USER: 'imageboard'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306:3306"